(function($) {
    $(document).ready(function() {
	
	$('#changepoints').scianimator({
	    'images': ['images/changepoints1.png', 'images/changepoints2.png', 'images/changepoints3.png', 'images/changepoints4.png', 'images/changepoints5.png', 'images/changepoints6.png', 'images/changepoints7.png', 'images/changepoints8.png', 'images/changepoints9.png', 'images/changepoints10.png', 'images/changepoints11.png', 'images/changepoints12.png', 'images/changepoints13.png', 'images/changepoints14.png', 'images/changepoints15.png', 'images/changepoints16.png', 'images/changepoints17.png', 'images/changepoints18.png', 'images/changepoints19.png', 'images/changepoints20.png', 'images/changepoints21.png', 'images/changepoints22.png', 'images/changepoints23.png', 'images/changepoints24.png', 'images/changepoints25.png', 'images/changepoints26.png', 'images/changepoints27.png', 'images/changepoints28.png', 'images/changepoints29.png', 'images/changepoints30.png', 'images/changepoints31.png', 'images/changepoints32.png', 'images/changepoints33.png', 'images/changepoints34.png', 'images/changepoints35.png', 'images/changepoints36.png', 'images/changepoints37.png', 'images/changepoints38.png', 'images/changepoints39.png', 'images/changepoints40.png', 'images/changepoints41.png', 'images/changepoints42.png', 'images/changepoints43.png', 'images/changepoints44.png', 'images/changepoints45.png', 'images/changepoints46.png', 'images/changepoints47.png', 'images/changepoints48.png', 'images/changepoints49.png', 'images/changepoints50.png', 'images/changepoints51.png', 'images/changepoints52.png', 'images/changepoints53.png', 'images/changepoints54.png', 'images/changepoints55.png', 'images/changepoints56.png', 'images/changepoints57.png', 'images/changepoints58.png', 'images/changepoints59.png', 'images/changepoints60.png', 'images/changepoints61.png', 'images/changepoints62.png', 'images/changepoints63.png', 'images/changepoints64.png', 'images/changepoints65.png', 'images/changepoints66.png', 'images/changepoints67.png', 'images/changepoints68.png', 'images/changepoints69.png', 'images/changepoints70.png', 'images/changepoints71.png', 'images/changepoints72.png', 'images/changepoints73.png', 'images/changepoints74.png', 'images/changepoints75.png', 'images/changepoints76.png', 'images/changepoints77.png', 'images/changepoints78.png', 'images/changepoints79.png', 'images/changepoints80.png', 'images/changepoints81.png', 'images/changepoints82.png', 'images/changepoints83.png', 'images/changepoints84.png', 'images/changepoints85.png', 'images/changepoints86.png', 'images/changepoints87.png', 'images/changepoints88.png', 'images/changepoints89.png', 'images/changepoints90.png'],
	    'width': 480,
	    'delay': 200,
	    'loopMode': 'loop'
	});
	$('#changepoints').scianimator('play');
    });
})(jQuery);
