(function($) {
    $(document).ready(function() {
	
	$('#changepoints_k_3').scianimator({
	    'images': ['images/changepoints_k_31.png', 'images/changepoints_k_32.png', 'images/changepoints_k_33.png', 'images/changepoints_k_34.png', 'images/changepoints_k_35.png', 'images/changepoints_k_36.png', 'images/changepoints_k_37.png', 'images/changepoints_k_38.png', 'images/changepoints_k_39.png', 'images/changepoints_k_310.png', 'images/changepoints_k_311.png', 'images/changepoints_k_312.png', 'images/changepoints_k_313.png', 'images/changepoints_k_314.png', 'images/changepoints_k_315.png', 'images/changepoints_k_316.png', 'images/changepoints_k_317.png', 'images/changepoints_k_318.png', 'images/changepoints_k_319.png', 'images/changepoints_k_320.png', 'images/changepoints_k_321.png', 'images/changepoints_k_322.png', 'images/changepoints_k_323.png', 'images/changepoints_k_324.png', 'images/changepoints_k_325.png', 'images/changepoints_k_326.png', 'images/changepoints_k_327.png', 'images/changepoints_k_328.png', 'images/changepoints_k_329.png', 'images/changepoints_k_330.png', 'images/changepoints_k_331.png', 'images/changepoints_k_332.png', 'images/changepoints_k_333.png', 'images/changepoints_k_334.png', 'images/changepoints_k_335.png', 'images/changepoints_k_336.png', 'images/changepoints_k_337.png', 'images/changepoints_k_338.png', 'images/changepoints_k_339.png', 'images/changepoints_k_340.png', 'images/changepoints_k_341.png', 'images/changepoints_k_342.png', 'images/changepoints_k_343.png', 'images/changepoints_k_344.png', 'images/changepoints_k_345.png', 'images/changepoints_k_346.png', 'images/changepoints_k_347.png', 'images/changepoints_k_348.png', 'images/changepoints_k_349.png', 'images/changepoints_k_350.png', 'images/changepoints_k_351.png', 'images/changepoints_k_352.png', 'images/changepoints_k_353.png', 'images/changepoints_k_354.png', 'images/changepoints_k_355.png', 'images/changepoints_k_356.png', 'images/changepoints_k_357.png', 'images/changepoints_k_358.png', 'images/changepoints_k_359.png', 'images/changepoints_k_360.png', 'images/changepoints_k_361.png', 'images/changepoints_k_362.png', 'images/changepoints_k_363.png', 'images/changepoints_k_364.png', 'images/changepoints_k_365.png', 'images/changepoints_k_366.png', 'images/changepoints_k_367.png', 'images/changepoints_k_368.png', 'images/changepoints_k_369.png', 'images/changepoints_k_370.png', 'images/changepoints_k_371.png', 'images/changepoints_k_372.png', 'images/changepoints_k_373.png', 'images/changepoints_k_374.png', 'images/changepoints_k_375.png', 'images/changepoints_k_376.png', 'images/changepoints_k_377.png', 'images/changepoints_k_378.png', 'images/changepoints_k_379.png', 'images/changepoints_k_380.png', 'images/changepoints_k_381.png', 'images/changepoints_k_382.png', 'images/changepoints_k_383.png', 'images/changepoints_k_384.png', 'images/changepoints_k_385.png', 'images/changepoints_k_386.png', 'images/changepoints_k_387.png', 'images/changepoints_k_388.png', 'images/changepoints_k_389.png', 'images/changepoints_k_390.png'],
	    'width': 480,
	    'delay': 200,
	    'loopMode': 'none'
	});
	$('#changepoints_k_3').scianimator('play');
    });
})(jQuery);
