(function($) {
    $(document).ready(function() {
	
	$('#micro_lines_plot').scianimator({
	    'images': ['images/micro_lines_plot1.png', 'images/micro_lines_plot2.png', 'images/micro_lines_plot3.png', 'images/micro_lines_plot4.png', 'images/micro_lines_plot5.png', 'images/micro_lines_plot6.png', 'images/micro_lines_plot7.png', 'images/micro_lines_plot8.png', 'images/micro_lines_plot9.png', 'images/micro_lines_plot10.png', 'images/micro_lines_plot11.png', 'images/micro_lines_plot12.png', 'images/micro_lines_plot13.png', 'images/micro_lines_plot14.png', 'images/micro_lines_plot15.png', 'images/micro_lines_plot16.png', 'images/micro_lines_plot17.png', 'images/micro_lines_plot18.png', 'images/micro_lines_plot19.png', 'images/micro_lines_plot20.png', 'images/micro_lines_plot21.png', 'images/micro_lines_plot22.png', 'images/micro_lines_plot23.png', 'images/micro_lines_plot24.png', 'images/micro_lines_plot25.png', 'images/micro_lines_plot26.png', 'images/micro_lines_plot27.png', 'images/micro_lines_plot28.png', 'images/micro_lines_plot29.png', 'images/micro_lines_plot30.png', 'images/micro_lines_plot31.png', 'images/micro_lines_plot32.png', 'images/micro_lines_plot33.png', 'images/micro_lines_plot34.png', 'images/micro_lines_plot35.png', 'images/micro_lines_plot36.png', 'images/micro_lines_plot37.png', 'images/micro_lines_plot38.png', 'images/micro_lines_plot39.png', 'images/micro_lines_plot40.png', 'images/micro_lines_plot41.png', 'images/micro_lines_plot42.png', 'images/micro_lines_plot43.png', 'images/micro_lines_plot44.png', 'images/micro_lines_plot45.png', 'images/micro_lines_plot46.png', 'images/micro_lines_plot47.png', 'images/micro_lines_plot48.png', 'images/micro_lines_plot49.png', 'images/micro_lines_plot50.png', 'images/micro_lines_plot51.png', 'images/micro_lines_plot52.png', 'images/micro_lines_plot53.png', 'images/micro_lines_plot54.png', 'images/micro_lines_plot55.png', 'images/micro_lines_plot56.png', 'images/micro_lines_plot57.png', 'images/micro_lines_plot58.png', 'images/micro_lines_plot59.png', 'images/micro_lines_plot60.png', 'images/micro_lines_plot61.png', 'images/micro_lines_plot62.png', 'images/micro_lines_plot63.png', 'images/micro_lines_plot64.png', 'images/micro_lines_plot65.png', 'images/micro_lines_plot66.png', 'images/micro_lines_plot67.png', 'images/micro_lines_plot68.png', 'images/micro_lines_plot69.png', 'images/micro_lines_plot70.png', 'images/micro_lines_plot71.png', 'images/micro_lines_plot72.png', 'images/micro_lines_plot73.png', 'images/micro_lines_plot74.png', 'images/micro_lines_plot75.png', 'images/micro_lines_plot76.png', 'images/micro_lines_plot77.png', 'images/micro_lines_plot78.png', 'images/micro_lines_plot79.png', 'images/micro_lines_plot80.png', 'images/micro_lines_plot81.png', 'images/micro_lines_plot82.png', 'images/micro_lines_plot83.png', 'images/micro_lines_plot84.png', 'images/micro_lines_plot85.png', 'images/micro_lines_plot86.png', 'images/micro_lines_plot87.png', 'images/micro_lines_plot88.png', 'images/micro_lines_plot89.png', 'images/micro_lines_plot90.png'],
	    'width': 480,
	    'delay': 500,
	    'loopMode': 'loop'
	});
	$('#micro_lines_plot').scianimator('play');
    });
})(jQuery);
