(function($) {
    $(document).ready(function() {
	
	$('#nice_stripe_k_4').scianimator({
	    'images': ['images/nice_stripe_k_41.png', 'images/nice_stripe_k_42.png', 'images/nice_stripe_k_43.png', 'images/nice_stripe_k_44.png', 'images/nice_stripe_k_45.png', 'images/nice_stripe_k_46.png', 'images/nice_stripe_k_47.png', 'images/nice_stripe_k_48.png', 'images/nice_stripe_k_49.png', 'images/nice_stripe_k_410.png', 'images/nice_stripe_k_411.png', 'images/nice_stripe_k_412.png', 'images/nice_stripe_k_413.png', 'images/nice_stripe_k_414.png', 'images/nice_stripe_k_415.png', 'images/nice_stripe_k_416.png', 'images/nice_stripe_k_417.png', 'images/nice_stripe_k_418.png', 'images/nice_stripe_k_419.png', 'images/nice_stripe_k_420.png', 'images/nice_stripe_k_421.png', 'images/nice_stripe_k_422.png', 'images/nice_stripe_k_423.png', 'images/nice_stripe_k_424.png', 'images/nice_stripe_k_425.png', 'images/nice_stripe_k_426.png', 'images/nice_stripe_k_427.png', 'images/nice_stripe_k_428.png', 'images/nice_stripe_k_429.png', 'images/nice_stripe_k_430.png', 'images/nice_stripe_k_431.png', 'images/nice_stripe_k_432.png', 'images/nice_stripe_k_433.png', 'images/nice_stripe_k_434.png', 'images/nice_stripe_k_435.png', 'images/nice_stripe_k_436.png', 'images/nice_stripe_k_437.png', 'images/nice_stripe_k_438.png', 'images/nice_stripe_k_439.png', 'images/nice_stripe_k_440.png', 'images/nice_stripe_k_441.png', 'images/nice_stripe_k_442.png', 'images/nice_stripe_k_443.png', 'images/nice_stripe_k_444.png', 'images/nice_stripe_k_445.png', 'images/nice_stripe_k_446.png', 'images/nice_stripe_k_447.png', 'images/nice_stripe_k_448.png', 'images/nice_stripe_k_449.png', 'images/nice_stripe_k_450.png', 'images/nice_stripe_k_451.png', 'images/nice_stripe_k_452.png', 'images/nice_stripe_k_453.png', 'images/nice_stripe_k_454.png', 'images/nice_stripe_k_455.png', 'images/nice_stripe_k_456.png', 'images/nice_stripe_k_457.png', 'images/nice_stripe_k_458.png', 'images/nice_stripe_k_459.png', 'images/nice_stripe_k_460.png', 'images/nice_stripe_k_461.png', 'images/nice_stripe_k_462.png', 'images/nice_stripe_k_463.png', 'images/nice_stripe_k_464.png', 'images/nice_stripe_k_465.png', 'images/nice_stripe_k_466.png', 'images/nice_stripe_k_467.png', 'images/nice_stripe_k_468.png', 'images/nice_stripe_k_469.png', 'images/nice_stripe_k_470.png', 'images/nice_stripe_k_471.png', 'images/nice_stripe_k_472.png', 'images/nice_stripe_k_473.png', 'images/nice_stripe_k_474.png', 'images/nice_stripe_k_475.png', 'images/nice_stripe_k_476.png', 'images/nice_stripe_k_477.png', 'images/nice_stripe_k_478.png', 'images/nice_stripe_k_479.png', 'images/nice_stripe_k_480.png', 'images/nice_stripe_k_481.png', 'images/nice_stripe_k_482.png', 'images/nice_stripe_k_483.png', 'images/nice_stripe_k_484.png', 'images/nice_stripe_k_485.png', 'images/nice_stripe_k_486.png', 'images/nice_stripe_k_487.png', 'images/nice_stripe_k_488.png', 'images/nice_stripe_k_489.png', 'images/nice_stripe_k_490.png'],
	    'width': 480,
	    'delay': 200,
	    'loopMode': 'none'
	});
	$('#nice_stripe_k_4').scianimator('play');
    });
})(jQuery);
