(function($) {
    $(document).ready(function() {
	
	$('#nice_stripe_k_5').scianimator({
	    'images': ['images/nice_stripe_k_51.png', 'images/nice_stripe_k_52.png', 'images/nice_stripe_k_53.png', 'images/nice_stripe_k_54.png', 'images/nice_stripe_k_55.png', 'images/nice_stripe_k_56.png', 'images/nice_stripe_k_57.png', 'images/nice_stripe_k_58.png', 'images/nice_stripe_k_59.png', 'images/nice_stripe_k_510.png', 'images/nice_stripe_k_511.png', 'images/nice_stripe_k_512.png', 'images/nice_stripe_k_513.png', 'images/nice_stripe_k_514.png', 'images/nice_stripe_k_515.png', 'images/nice_stripe_k_516.png', 'images/nice_stripe_k_517.png', 'images/nice_stripe_k_518.png', 'images/nice_stripe_k_519.png', 'images/nice_stripe_k_520.png', 'images/nice_stripe_k_521.png', 'images/nice_stripe_k_522.png', 'images/nice_stripe_k_523.png', 'images/nice_stripe_k_524.png', 'images/nice_stripe_k_525.png', 'images/nice_stripe_k_526.png', 'images/nice_stripe_k_527.png', 'images/nice_stripe_k_528.png', 'images/nice_stripe_k_529.png', 'images/nice_stripe_k_530.png', 'images/nice_stripe_k_531.png', 'images/nice_stripe_k_532.png', 'images/nice_stripe_k_533.png', 'images/nice_stripe_k_534.png', 'images/nice_stripe_k_535.png', 'images/nice_stripe_k_536.png', 'images/nice_stripe_k_537.png', 'images/nice_stripe_k_538.png', 'images/nice_stripe_k_539.png', 'images/nice_stripe_k_540.png', 'images/nice_stripe_k_541.png', 'images/nice_stripe_k_542.png', 'images/nice_stripe_k_543.png', 'images/nice_stripe_k_544.png', 'images/nice_stripe_k_545.png', 'images/nice_stripe_k_546.png', 'images/nice_stripe_k_547.png', 'images/nice_stripe_k_548.png', 'images/nice_stripe_k_549.png', 'images/nice_stripe_k_550.png', 'images/nice_stripe_k_551.png', 'images/nice_stripe_k_552.png', 'images/nice_stripe_k_553.png', 'images/nice_stripe_k_554.png', 'images/nice_stripe_k_555.png', 'images/nice_stripe_k_556.png', 'images/nice_stripe_k_557.png', 'images/nice_stripe_k_558.png', 'images/nice_stripe_k_559.png', 'images/nice_stripe_k_560.png', 'images/nice_stripe_k_561.png', 'images/nice_stripe_k_562.png', 'images/nice_stripe_k_563.png', 'images/nice_stripe_k_564.png', 'images/nice_stripe_k_565.png', 'images/nice_stripe_k_566.png', 'images/nice_stripe_k_567.png', 'images/nice_stripe_k_568.png', 'images/nice_stripe_k_569.png', 'images/nice_stripe_k_570.png', 'images/nice_stripe_k_571.png', 'images/nice_stripe_k_572.png', 'images/nice_stripe_k_573.png', 'images/nice_stripe_k_574.png', 'images/nice_stripe_k_575.png', 'images/nice_stripe_k_576.png', 'images/nice_stripe_k_577.png', 'images/nice_stripe_k_578.png', 'images/nice_stripe_k_579.png', 'images/nice_stripe_k_580.png', 'images/nice_stripe_k_581.png', 'images/nice_stripe_k_582.png', 'images/nice_stripe_k_583.png', 'images/nice_stripe_k_584.png', 'images/nice_stripe_k_585.png', 'images/nice_stripe_k_586.png', 'images/nice_stripe_k_587.png', 'images/nice_stripe_k_588.png', 'images/nice_stripe_k_589.png', 'images/nice_stripe_k_590.png'],
	    'width': 480,
	    'delay': 200,
	    'loopMode': 'none'
	});
	$('#nice_stripe_k_5').scianimator('play');
    });
})(jQuery);
